# file: .github/workflows/main.yml
name: check actions
# on – определяет события, которые запускают воркфлоу
on: push
# Пример для проекта на Node.js
jobs:
  check: # имя взято для примера
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - run: echo "Имя текущего воркфлоу – $GITHUB_WORKFLOW"
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      # Ставим зависимости
      - run: make setup
      # Запускаем линтер
      - run: make lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name
